name: Conda Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge. # , defaults
          activate-environment: scipy
          python-version: 3.12

      - name: Install conda packages
        shell: pwsh
        run: |
          conda install numpy scipy dipy

      - name: Hello World
        shell: pwsh
        run: |
          python -c "import numpy as np; print('Numpy version: '+np.__version__)"
          python -c "import scipy as sp; print('Scipy version: '+sp.__version__)"
          python -c "import dipy; print('DIPY version: '+dipy.__version__)"